services:
  walkietalkie:
    build: .
    container_name: walkietalkie
    restart: unless-stopped
    ports:
      - "8083:8083"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
